name: Regent-FFT Tests

run-name: ${{ github.actor }} is testing Regent-FFT

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  regent-FFT-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run clang-format
        run: |
          clang-format -i test/*.{h,cc}
          git status
          git diff

      - name: Run tests
        run: ./test.sh
